// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/aws/bedrock_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBedrockClientInterface is a mock of BedrockClientInterface interface.
type MockBedrockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBedrockClientInterfaceMockRecorder
}

// MockBedrockClientInterfaceMockRecorder is the mock recorder for MockBedrockClientInterface.
type MockBedrockClientInterfaceMockRecorder struct {
	mock *MockBedrockClientInterface
}

// NewMockBedrockClientInterface creates a new mock instance.
func NewMockBedrockClientInterface(ctrl *gomock.Controller) *MockBedrockClientInterface {
	mock := &MockBedrockClientInterface{ctrl: ctrl}
	mock.recorder = &MockBedrockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBedrockClientInterface) EXPECT() *MockBedrockClientInterfaceMockRecorder {
	return m.recorder
}

// GenerateEmbedding mocks base method.
func (m *MockBedrockClientInterface) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockBedrockClientInterfaceMockRecorder) GenerateEmbedding(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockBedrockClientInterface)(nil).GenerateEmbedding), ctx, text)
}

// GenerateSummary mocks base method.
func (m *MockBedrockClientInterface) GenerateSummary(ctx context.Context, text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSummary", ctx, text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSummary indicates an expected call of GenerateSummary.
func (mr *MockBedrockClientInterfaceMockRecorder) GenerateSummary(ctx, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSummary", reflect.TypeOf((*MockBedrockClientInterface)(nil).GenerateSummary), ctx, text)
}

// GenerateText mocks base method.
func (m *MockBedrockClientInterface) GenerateText(ctx context.Context, prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateText", ctx, prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateText indicates an expected call of GenerateText.
func (mr *MockBedrockClientInterfaceMockRecorder) GenerateText(ctx, prompt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateText", reflect.TypeOf((*MockBedrockClientInterface)(nil).GenerateText), ctx, prompt)
}
