name: Backend CI

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        go-version: ['1.22'] # Specify your Go version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: backend/go.sum # Specify path to lock file

      - name: Install dependencies
        run: go mod download

      # Uncomment if you add linters (e.g., golangci-lint)
      # - name: Run linters
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: latest # Or specify a fixed version
      #     working-directory: backend

      - name: Run tests
        run: go test ./... -v

      - name: Build project
        run: go build -v ./...
